apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: scraper
  name: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scraper
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: scraper
    spec:
      containers:
        - image: registry.digitalocean.com/rso-registry/scraper
          name: scraper
          livenessProbe:
              httpGet:
                path: /healthz
                port: 3001
              initialDelaySeconds: 5
              periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 20
      restartPolicy: Always
