apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: notification
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notification
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: notification
    spec:
      containers:
        - env:
            - name: MONGODB_URL
              value: mongodb://mongodb:27017/test
          image: registry.digitalocean.com/rso-registry/notification
          name: notification
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
