apiVersion: v1
kind: Service
metadata:
  name: web-cluster-ip
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    io.kompose.service: web
  type: ClusterIP