apiVersion: apps/v1
kind: Deployment
metadata:
  name: extreme-weather-event-notifier-deployment
  labels:
    app: extreme-weather-event-notifier
    tier: backend
    environment: development
    app.kubernetes.io/name: extreme-weather-event-notifier
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
      containers:
        - name: web
          image: registry.digitalocean.com/rso-registry/web:test
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 20
      imagePullSecrets:
        - name: rso-registry
