services:
  notification:
    container_name: notification
    restart: always
    build: .
    ports:
      - '3001:3001'
    networks:
      - notification-network
      - rabbitmq-network
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    hostname: mongodb
    image: mongo:8.0.4-rc0-noble
    volumes:
      - ./conduit:/data/db/
    ports:
      - '27017:27017'
    networks:
      - notification-network
networks:
  notification-network:
    driver: bridge
  rabbitmq-network:
    external: true
