services:
  notification:
    container_name: notification
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./:/app/
    networks:
      - notification-network
      - rabbitmq-network
    depends_on:
      - notification-mongo
  notification-mongo:
    container_name: notification-mongo
    hostname: notification-mongo
    image: mongo:8.0.4-rc0-noble
    volumes:
      - ./conduit:/data/db/
    ports:
      - '27017:27017'
    networks:
      - notification-network
networks:
  notification-network:
    external: true
  rabbitmq-network:
    external: true
