services:
  notification:
    container_name: notification
    restart: always
    build: .
    ports:
      - '3001:3001'
    # volumes:
    #   - ./src:/app/src
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/test
    networks:
      - mongo-network
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    hostname: mongodb
    image: mongo:8.0.4-rc0-noble
    volumes:
      - ./conduit:/data/db/
    ports:
      - '27017:27017'
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
