apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: storage
    spec:
      containers:
        - image: registry.digitalocean.com/rso-registry/storage
          name: storage
          ports:
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always
