apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: storage-mongodb
  name: storage-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: storage-mongodb
    spec:
      containers:
        - args:
            - mongod
            - --port
            - "27018"
          image: mongo:8.0.4-rc0-noble
          name: storage-mongodb
          ports:
            - containerPort: 27018
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: storage-mongodb-claim0
      hostname: storage-mongodb
      restartPolicy: Always
      volumes:
        - name: storage-mongodb-claim0
          persistentVolumeClaim:
            claimName: storage-mongodb-claim0
