name: Notification service tests

on:
  push:
    paths:
      - notification/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./notification

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build
      - run: npm run lint
