services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    networks:
      - notification-network
      - storage-network
networks:
  notification-network:
    external: true
  storage-network:
    external: true
